#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Playfie.Droid.Resource", IsApplication=true)]

namespace Playfie.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::Playfie.Droid.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int animAlpha = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int animJumper = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01002a
			public const int civ_border_color = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int civ_border_overlay = 2130772011;
			
			// aapt resource value: 0x7f010029
			public const int civ_border_width = 2130772009;
			
			// aapt resource value: 0x7f01002c
			public const int civ_fill_color = 2130772012;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010021
			public const int com_facebook_auxiliary_view_position = 2130772001;
			
			// aapt resource value: 0x7f010023
			public const int com_facebook_confirm_logout = 2130772003;
			
			// aapt resource value: 0x7f01001d
			public const int com_facebook_foreground_color = 2130771997;
			
			// aapt resource value: 0x7f010022
			public const int com_facebook_horizontal_alignment = 2130772002;
			
			// aapt resource value: 0x7f010028
			public const int com_facebook_is_cropped = 2130772008;
			
			// aapt resource value: 0x7f010024
			public const int com_facebook_login_text = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int com_facebook_logout_text = 2130772005;
			
			// aapt resource value: 0x7f01001e
			public const int com_facebook_object_id = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int com_facebook_object_type = 2130771999;
			
			// aapt resource value: 0x7f010027
			public const int com_facebook_preset_size = 2130772007;
			
			// aapt resource value: 0x7f010020
			public const int com_facebook_style = 2130772000;
			
			// aapt resource value: 0x7f010026
			public const int com_facebook_tooltip_mode = 2130772006;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060015
			public const int btn_1 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int btn_2 = 2131099670;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_blue = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_button_background_color = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_button_background_color_disabled = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_button_background_color_pressed = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_button_like_background_color_selected = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_button_login_silver_background_color = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_button_login_silver_background_color_pressed = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_button_send_background_color = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_button_send_background_color_pressed = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_likeboxcountview_border_color = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_likeboxcountview_text_color = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_likeview_text_color = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_share_button_text_color = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int common_google_signin_btn_text_dark = 2131099671;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int common_google_signin_btn_text_light = 2131099672;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f060019
			public const int common_google_signin_btn_tint = 2131099673;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int com_facebook_likeboxcountview_border_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int com_facebook_likeboxcountview_border_width = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int com_facebook_likeboxcountview_caret_height = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int com_facebook_likeboxcountview_caret_width = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int com_facebook_likeboxcountview_text_padding = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int com_facebook_likeboxcountview_text_size = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int com_facebook_likeview_edge_padding = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int com_facebook_likeview_internal_padding = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int com_facebook_likeview_text_size = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int com_facebook_profilepictureview_preset_size_large = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int com_facebook_share_button_padding_bottom = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int com_facebook_share_button_padding_left = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int com_facebook_share_button_padding_right = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int com_facebook_share_button_padding_top = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int com_facebook_share_button_text_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int com_facebook_tooltip_horizontal_padding = 2131296274;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_button_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_button_like_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_like_icon_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_login_silver_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_send_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_send_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_close = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_profile_picture_blank_portrait = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_profile_picture_blank_square = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_tooltip_black_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_tooltip_black_bottomnub = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_tooltip_black_topnub = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_tooltip_black_xout = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_tooltip_blue_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_tooltip_blue_bottomnub = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_tooltip_blue_topnub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_blue_xout = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_full_open_on_phone = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_icon_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_icon_dark_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_icon_dark_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_icon_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_icon_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_icon_light_focused = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_icon_light_normal = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_icon_light_normal_background = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_text_dark_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_text_dark_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_text_dark_normal_background = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_text_disabled = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_google_signin_btn_text_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_google_signin_btn_text_light_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_google_signin_btn_text_light_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_google_signin_btn_text_light_normal_background = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int googleg_disabled_color_18 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int googleg_standard_color_18 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int loginFacebook = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int messenger_bubble_large_blue = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int messenger_bubble_large_white = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int messenger_bubble_small_blue = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int messenger_bubble_small_white = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int messenger_button_blue_bg_round = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int messenger_button_blue_bg_selector = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int messenger_button_send_round_shadow = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int messenger_button_white_bg_round = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int messenger_button_white_bg_selector = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int playfieIcon = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int round_btn = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0005
			public const int adjust_height = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int adjust_width = 2131427334;
			
			// aapt resource value: 0x7f0b000a
			public const int auto = 2131427338;
			
			// aapt resource value: 0x7f0b0018
			public const int automatic = 2131427352;
			
			// aapt resource value: 0x7f0b0012
			public const int bottom = 2131427346;
			
			// aapt resource value: 0x7f0b0010
			public const int box_count = 2131427344;
			
			// aapt resource value: 0x7f0b0025
			public const int btnLoginFB = 2131427365;
			
			// aapt resource value: 0x7f0b0031
			public const int btnNext = 2131427377;
			
			// aapt resource value: 0x7f0b002c
			public const int btnPhoto = 2131427372;
			
			// aapt resource value: 0x7f0b002a
			public const int btnSignIn = 2131427370;
			
			// aapt resource value: 0x7f0b0029
			public const int btnSignUp = 2131427369;
			
			// aapt resource value: 0x7f0b0011
			public const int button = 2131427345;
			
			// aapt resource value: 0x7f0b0015
			public const int center = 2131427349;
			
			// aapt resource value: 0x7f0b001f
			public const int com_facebook_body_frame = 2131427359;
			
			// aapt resource value: 0x7f0b0021
			public const int com_facebook_button_xout = 2131427361;
			
			// aapt resource value: 0x7f0b001d
			public const int com_facebook_fragment_container = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int com_facebook_login_activity_progress_bar = 2131427358;
			
			// aapt resource value: 0x7f0b0023
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131427363;
			
			// aapt resource value: 0x7f0b0022
			public const int com_facebook_tooltip_bubble_view_text_body = 2131427362;
			
			// aapt resource value: 0x7f0b0020
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131427360;
			
			// aapt resource value: 0x7f0b000b
			public const int dark = 2131427339;
			
			// aapt resource value: 0x7f0b0019
			public const int display_always = 2131427353;
			
			// aapt resource value: 0x7f0b0027
			public const int etLogin = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int etPassword = 2131427368;
			
			// aapt resource value: 0x7f0b0000
			public const int hybrid = 2131427328;
			
			// aapt resource value: 0x7f0b0007
			public const int icon_only = 2131427335;
			
			// aapt resource value: 0x7f0b0013
			public const int inline = 2131427347;
			
			// aapt resource value: 0x7f0b0024
			public const int ivAppIcon = 2131427364;
			
			// aapt resource value: 0x7f0b002f
			public const int ivAvatar = 2131427375;
			
			// aapt resource value: 0x7f0b001b
			public const int large = 2131427355;
			
			// aapt resource value: 0x7f0b0016
			public const int left = 2131427350;
			
			// aapt resource value: 0x7f0b000c
			public const int light = 2131427340;
			
			// aapt resource value: 0x7f0b002b
			public const int messenger_send_button = 2131427371;
			
			// aapt resource value: 0x7f0b001a
			public const int never_display = 2131427354;
			
			// aapt resource value: 0x7f0b0001
			public const int none = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int normal = 2131427330;
			
			// aapt resource value: 0x7f0b000d
			public const int open_graph = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int page = 2131427342;
			
			// aapt resource value: 0x7f0b0017
			public const int right = 2131427351;
			
			// aapt resource value: 0x7f0b0003
			public const int satellite = 2131427331;
			
			// aapt resource value: 0x7f0b001c
			public const int small = 2131427356;
			
			// aapt resource value: 0x7f0b0008
			public const int standard = 2131427336;
			
			// aapt resource value: 0x7f0b0004
			public const int terrain = 2131427332;
			
			// aapt resource value: 0x7f0b002d
			public const int tlTip1 = 2131427373;
			
			// aapt resource value: 0x7f0b002e
			public const int tlTip2 = 2131427374;
			
			// aapt resource value: 0x7f0b0030
			public const int tlTip3 = 2131427376;
			
			// aapt resource value: 0x7f0b0014
			public const int top = 2131427348;
			
			// aapt resource value: 0x7f0b0026
			public const int tvOr = 2131427366;
			
			// aapt resource value: 0x7f0b000f
			public const int unknown = 2131427343;
			
			// aapt resource value: 0x7f0b0009
			public const int wide = 2131427337;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int com_facebook_activity_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int com_facebook_login_fragment = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_tooltip_bubble = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int messenger_button_send_blue_large = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int messenger_button_send_blue_round = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int messenger_button_send_blue_small = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int messenger_button_send_white_large = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int messenger_button_send_white_round = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int messenger_button_send_white_small = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int PhotoTutorial = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int PhotoTutorialResult = 2130968587;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int playfieIcon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070023
			public const int app_name = 2131165219;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_image_download_unknown_error = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_internet_permission_error_message = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_internet_permission_error_title = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int com_facebook_like_button_liked = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int com_facebook_like_button_not_liked = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int com_facebook_loading = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int com_facebook_loginview_cancel_action = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int com_facebook_loginview_log_in_button = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int com_facebook_loginview_log_in_button_long = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int com_facebook_loginview_log_out_action = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int com_facebook_loginview_log_out_button = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int com_facebook_loginview_logged_in_as = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int com_facebook_loginview_logged_in_using_facebook = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int com_facebook_send_button_text = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int com_facebook_share_button_text = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int com_facebook_tooltip_default = 2131165216;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_enable_button = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_enable_text = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_enable_title = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_button = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_install_text = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_install_title = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_notification_ticker = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_unknown_issue = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_unsupported_text = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_button = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_update_text = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_update_title = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_updating_text = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_wear_update_text = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int common_open_on_phone = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int common_signin_button_text = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int common_signin_button_text_long = 2131165199;
			
			// aapt resource value: 0x7f070024
			public const int facebook_app_id = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int fb_login_protocol_scheme = 2131165221;
			
			// aapt resource value: 0x7f07002c
			public const int google_maps_key = 2131165228;
			
			// aapt resource value: 0x7f070022
			public const int library_name = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int messenger_send_button_text = 2131165217;
			
			// aapt resource value: 0x7f070028
			public const int need_account = 2131165224;
			
			// aapt resource value: 0x7f07002b
			public const int next = 2131165227;
			
			// aapt resource value: 0x7f070026
			public const int placeholder_email = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int placeholder_password = 2131165223;
			
			// aapt resource value: 0x7f070029
			public const int sign_in = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int sign_up = 2131165226;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int MessengerButton = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int MessengerButton_Blue = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int MessengerButton_Blue_Large = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int MessengerButton_Blue_Small = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int MessengerButton_White = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int MessengerButton_White_Large = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int MessengerButton_White_Small = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int MessengerButtonText = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int MessengerButtonText_Blue = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int MessengerButtonText_Blue_Large = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int MessengerButtonText_Blue_Small = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int MessengerButtonText_White = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int MessengerButtonText_White_Large = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int MessengerButtonText_White_Small = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int com_facebook_button = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int com_facebook_button_like = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int com_facebook_button_send = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int com_facebook_button_share = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int com_facebook_loginview_default_style = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int com_facebook_loginview_silver_style = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int tooltip_bubble_text = 2131361812;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130772009,
					2130772010,
					2130772011,
					2130772012};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130772003,
					2130772004,
					2130772005,
					2130772006};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130772007,
					2130772008};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
